### ISSUE TITLE
Loading styles. Content attribute not working. 

### ISSUE THREAD

**Issue by thsorens** [rmariuzzo/react-new-window#27] opened 2019-02-25 20:58 UTC
When using ex font-awesome or some other library that provides icons as a font, the font is not working in the opened window. I can see that the styles for it is copied over, but the content part of the style is not put in properly.

**Comment by yakaldir** [comment] 2019-08-27 09:54
same for usage like:
`.check-toggle {
    -webkit-mask-image: url(../images/check.svg);
    mask-image: url(../images/check.svg);
}`
check.svg is not copied

**Comment by Hinaser** [comment] 2020-02-16 23:37
Hi
I came across the same issue and understand the root cause.

When copying css styles from original window, the function below will be called.

![image](https://user-images.githubusercontent.com/12316730/74614398-f191eb80-515a-11ea-8d82-851c178d4eca.png)

The problem is, when trying to copy styles from `<link rel='stylesheet' href=<url> />`, sometimes it extracts css styles rules from the url specified at `href` attribute.
For @font-face css rule, it can specify font file location in relative path style.

So those relational path will be broken when the rule is extracted from css files and copied as plain `<style></style>` element.

For example, below is the case which breaks font-face rule.

![image](https://user-images.githubusercontent.com/12316730/74614771-25badb80-515e-11ea-9f8a-c6dd3174b39e.png)

In above case, `rules` variable in `copyStyles` function will not be empty and thus the css rules is pulled out from the css file.


I already send PR for this issue.
In case you can't wait until PR is merged, I also uploaded fixed version of this npm module.

You can specify fixed version of npm module like below in `package.json`.
Or just re-install react-new-window with my github repos branch.
`npm install --save Hinaser/react-new-window#npm-fix-external-font-not-loaded`

![image](https://user-images.githubusercontent.com/12316730/74614863-f8baf880-515e-11ea-8f7f-f835c419d19f.png)

**Comment by TravWill-Mongo** [comment] 2020-07-12 16:33
@Hinaser Just wanted to say thanks, your fix helped me with using Material UI in a NewWindow

**Comment by rmariuzzo** [comment] 2022-11-27 21:15
Release 1.0.1 include the fix provided by @Hinaser. [Here's a working example (click on `FontFace`)](https://codesandbox.io/s/react-new-window-issue-playground-4wbhyi?file=/src/issues/FontFace.tsx).

**Closed by rmariuzzo** 2022-11-27 21:15 UTC
