### ISSUE TITLE
onUnload triggers as soon as window is opened on Safari

### ISSUE THREAD

**Issue by superandrew213** [rmariuzzo/react-new-window#57] opened 2019-10-31 01:36 UTC
See example here: https://codesandbox.io/s/green-lake-n13i3

Use this url to test: https://n13i3.csb.app

Only happens on safari when using `url`.

**Comment by MkDevelop** [comment] 2019-12-06 16:15
The reason is that `beforeonunload` is triggered in different situations on safari see: https://webkit.org/blog/516/webkit-page-cache-ii-the-unload-event/
By replacing `this.window.addEventListener('beforeunload', () => this.release())` with `this.window.addEventListener('ononload', () => this.release())` the issue would be solved.

**Comment by vaneavasco** [comment] 2020-02-13 15:15
Guys, any updates? @rmariuzzo

**Comment by itzmanish** [comment] 2020-03-27 05:22
same issue on chrome here is example https://codesandbox.io/s/pensive-https-vnqin

**Comment by joelrojo** [comment] 2020-10-04 19:08
Any way we can get this in a new release @rmariuzzo ? Seems like a quick fix.

**Comment by rmariuzzo** [comment] 2020-10-05 02:40
@joelrojo will review it soon

**Comment by leehsueh** [comment] 2020-11-28 19:50
+1 for this to be fixed!

**Comment by Rigel772** [comment] 2020-12-16 10:22
same issue on Firefox

**Comment by rchiba** [comment] 2021-02-17 18:35
+1 on a fix for this

**Comment by dannypaz** [comment] 2021-02-23 09:18
@rchiba were you able to reproduce this? Im curious to know if this is a specific version of a browser or it happens for _all browsers_

**Comment by mattfrancis888** [comment] 2021-08-22 01:54
Has there been an official fix for this?

**Comment by kimgysen** [comment] 2021-12-30 10:41
Same issue on firefox 2021. Is the lib dead?

**Comment by FernandVEYRIER** [comment] 2022-03-14 15:25
The issue is still happening in Safari Version 15.2

**Comment by rmariuzzo** [comment] 2022-11-27 05:22
I just tried to reproduce this issue on Chrome, Safari and Firefox without success. It seems to have gone with recent published changes. Try updating to latest version of this package.

Note: before recent change, I did notice this issue.

**Closed by rmariuzzo** 2022-11-27 05:22 UTC
